use crate::protocol::{ObjectKind, ResourceKind};

use crate::sim::resources::ResourceNode;
use crate::sim::LifecycleFamily;

pub(in crate::sim) fn resource_node_for_object(
    kind: ObjectKind,
    object_id: &str,
) -> Option<ResourceNode> {
    match kind {
        ObjectKind::Grove => Some(ResourceNode {
            resource: ResourceKind::Wood,
            amount: 8,
            max_amount: 12,
            regen_per_second: 0.08,
            regen_progress: 0.0,
            lifecycle_family: LifecycleFamily::Tree,
            stage_override: None,
            species: Some("ashbark"),
            age_years: Some(84),
            age_progress_years: 0.0,
            base_health: 0.78,
        }),
        ObjectKind::Ore => Some(ResourceNode {
            resource: ResourceKind::Ore,
            amount: 6,
            max_amount: 8,
            regen_per_second: 0.025,
            regen_progress: 0.0,
            lifecycle_family: LifecycleFamily::Mineral,
            stage_override: None,
            species: None,
            age_years: None,
            age_progress_years: 0.0,
            base_health: 1.0,
        }),
        ObjectKind::Ruin => Some(ResourceNode {
            resource: ResourceKind::Stone,
            amount: 2,
            max_amount: 12,
            regen_per_second: 0.0,
            regen_progress: 0.0,
            lifecycle_family: LifecycleFamily::Mineral,
            stage_override: Some("ancient-ruin"),
            species: Some("sunken-viaduct-stone"),
            age_years: Some(128_000),
            age_progress_years: 0.0,
            base_health: 0.42,
        }),
        ObjectKind::Shrine => Some(ResourceNode {
            resource: ResourceKind::Mycelium,
            amount: 5,
            max_amount: 7,
            regen_per_second: 0.045,
            regen_progress: 0.0,
            lifecycle_family: LifecycleFamily::Mycelium,
            stage_override: None,
            species: Some("shrine-thread"),
            age_years: Some(19),
            age_progress_years: 0.0,
            base_health: 0.86,
        }),
        ObjectKind::SaplingTree if object_id == "mossheart-grove-tree" => Some(ResourceNode {
            resource: ResourceKind::Wood,
            amount: 9,
            max_amount: 12,
            regen_per_second: 0.05,
            regen_progress: 0.0,
            lifecycle_family: LifecycleFamily::Tree,
            stage_override: Some("mature"),
            species: Some("shadebark"),
            age_years: Some(64),
            age_progress_years: 0.0,
            base_health: 0.88,
        }),
        ObjectKind::SaplingTree if object_id == "ancient-ironleaf-tree" => Some(ResourceNode {
            resource: ResourceKind::Wood,
            amount: 12,
            max_amount: 12,
            regen_per_second: 0.018,
            regen_progress: 0.0,
            lifecycle_family: LifecycleFamily::Tree,
            stage_override: Some("ancient"),
            species: Some("ironleaf"),
            age_years: Some(183),
            age_progress_years: 0.0,
            base_health: 0.72,
        }),
        ObjectKind::SaplingTree => Some(ResourceNode {
            resource: ResourceKind::Seed,
            amount: 1,
            max_amount: 3,
            regen_per_second: 0.035,
            regen_progress: 0.0,
            lifecycle_family: LifecycleFamily::Tree,
            stage_override: Some("sapling"),
            species: Some("greenwood"),
            age_years: Some(7),
            age_progress_years: 0.0,
            base_health: 0.94,
        }),
        ObjectKind::Deadwood if object_id == "decaying-grove-stump" => Some(ResourceNode {
            resource: ResourceKind::Deadwood,
            amount: 2,
            max_amount: 5,
            regen_per_second: 0.0,
            regen_progress: 0.0,
            lifecycle_family: LifecycleFamily::Deadwood,
            stage_override: None,
            species: Some("mossheart-fall"),
            age_years: Some(9),
            age_progress_years: 0.0,
            base_health: 0.18,
        }),
        ObjectKind::Deadwood if object_id == "hollow-grove-stump" => Some(ResourceNode {
            resource: ResourceKind::Deadwood,
            amount: 1,
            max_amount: 5,
            regen_per_second: 0.0,
            regen_progress: 0.0,
            lifecycle_family: LifecycleFamily::Deadwood,
            stage_override: None,
            species: Some("hollow-ash"),
            age_years: Some(16),
            age_progress_years: 0.0,
            base_health: 0.12,
        }),
        ObjectKind::Deadwood => Some(ResourceNode {
            resource: ResourceKind::Deadwood,
            amount: 4,
            max_amount: 5,
            regen_per_second: 0.0,
            regen_progress: 0.0,
            lifecycle_family: LifecycleFamily::Deadwood,
            stage_override: None,
            species: Some("fallen-ash"),
            age_years: Some(3),
            age_progress_years: 0.0,
            base_health: 0.28,
        }),
        ObjectKind::MyceliumPatch if object_id == "veilcap-runner" => Some(ResourceNode {
            resource: ResourceKind::Mycelium,
            amount: 1,
            max_amount: 4,
            regen_per_second: 0.035,
            regen_progress: 0.0,
            lifecycle_family: LifecycleFamily::Mycelium,
            stage_override: None,
            species: Some("runner-veilcap"),
            age_years: Some(1),
            age_progress_years: 0.0,
            base_health: 0.78,
        }),
        ObjectKind::MyceliumPatch => Some(ResourceNode {
            resource: ResourceKind::Mycelium,
            amount: 3,
            max_amount: 4,
            regen_per_second: 0.055,
            regen_progress: 0.0,
            lifecycle_family: LifecycleFamily::Mycelium,
            stage_override: None,
            species: Some("veilcap"),
            age_years: Some(1),
            age_progress_years: 0.0,
            base_health: 0.9,
        }),
        ObjectKind::FieldCoil if object_id == "stormroot-field-coil" => Some(ResourceNode {
            resource: ResourceKind::Charge,
            amount: 1,
            max_amount: 3,
            regen_per_second: 0.0,
            regen_progress: 0.0,
            lifecycle_family: LifecycleFamily::Machine,
            stage_override: None,
            species: Some("stormroot"),
            age_years: Some(4),
            age_progress_years: 0.0,
            base_health: 0.62,
        }),
        ObjectKind::FieldCoil => Some(ResourceNode {
            resource: ResourceKind::Charge,
            amount: 3,
            max_amount: 5,
            regen_per_second: 0.065,
            regen_progress: 0.0,
            lifecycle_family: LifecycleFamily::Machine,
            stage_override: None,
            species: None,
            age_years: Some(12),
            age_progress_years: 0.0,
            base_health: 0.82,
        }),
        ObjectKind::Registrar | ObjectKind::Forge => None,
    }
}
